import { Container, Image, Text } from '@nextui-org/react';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import LinkList from '../components/link/LinkList';
import styles from '../styles/Home.module.css';

function Home({ links }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Diego Artiles - Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <Container css={{margin: '2rem 0'}}>
          <Image alt="dartiles logo" src="/logo.png" width={100} height={100} />
        </Container>
        <LinkList links={links} />
      </main>
    </div>
  )
}
export async function getServerSideProps({ req }) {
  console.log({ referer: req.headers.referer })
  const res = await fetch(`${req.headers.referer}api/links`)
  const data = await res.json()

  return { props: { links: data } }
}

export default Home