import { Avatar, Container, Image, StyledAvatar, StyledImage, Text } from "@nextui-org/react";
import absoluteUrl from "next-absolute-url";
import Head from "next/head";
import LinkList from "../components/link/LinkList";
import styles from "../styles/Home.module.css";

function Home({ links }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Diego Artiles - Centro de Enlaces</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <main className={styles.main}>
        <Container
          css={{
            position: "relative",
            margin: "2rem 0",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Avatar
            alt='diego face'
            src='https://dartiles.me/static/media/me.10078b41.png'
            bordered
            css={{
              margin: "$0",
              height: 200,
              width: 200,
              [`& img`]: {
                background: "$bodyBackground !important",
              },
            }}
          />
          <StyledImage
            alt='dartiles logo'
            src='/logo.png'
            css={{
              position: "absolute",
              margin: "$0",
              height: 40,
              width: 40,
              zIndex: 100,
              bottom: "-15px",
              padding: 10,
              background: "$white",
              borderRadius: "50%",
              border: "2px solid $accents2",
            }}
          />
        </Container>
        <Text h2 css={{ margin: "$10 $0" }}>
          Centro de Enlaces
        </Text>
        <LinkList links={links} />
      </main>
    </div>
  );
}
export async function getServerSideProps({ req }) {
  const { origin } = absoluteUrl(req);
  const res = await fetch(`${origin}/api/links`);
  const data = await res.json();

  return { props: { links: data } };
}

export default Home;
